const color = {
  lightBackgroundPrimary: 'rgba(243, 245, 247, 1)',
  lightBorderDisabled: 'rgba(24, 26, 28, 0.08)',
  lightBorderFocusedOnTint: 'rgba(0, 0, 0, 0.38)',
  lightBorderInverted: 'var(--ref-color-white)',
  lightBorderInvertedNone: 'rgba(255, 255, 255, 0)',
  lightBorderNone: 'rgba(0, 0, 0, 0)',
  lightBorderPrimary: 'rgba(24, 26, 28, 1)',
  lightBorderSecondary: 'rgba(24, 26, 28, 0.18)',
  lightBorderTertiary: 'rgba(24, 26, 28, 0.08)',
  lightFillDisabled: 'rgba(0, 0, 20, 0.1)',
  lightFillHovered: 'rgba(0, 0, 0, 0.04)',
  lightFillInverted: 'var(--ref-color-black)',
  lightFillInvertedNone: 'rgba(0, 0, 0, 0)',
  lightFillNone: 'rgba(0, 0, 51, 0)',
  lightFillPressed: 'rgba(0, 0, 0, 0.08)',
  lightFillPrimary: 'rgba(0, 0, 51, 0.04)',
  lightFillQuaternary: 'rgba(120, 120, 128, 0.08)',
  lightFillSecondary: 'rgba(0, 0, 20, 0.1)',
  lightFillTertiary: 'rgba(120, 120, 128, 0.12)',
  lightForegroundDisabled: 'rgba(24, 26, 28, 0.18)',
  lightForegroundInverted: 'rgba(255, 255, 255, 1)',
  lightForegroundInvertedNone: 'rgba(255, 255, 255, 0)',
  lightForegroundNone: 'rgba(24, 26, 28, 0)',
  lightForegroundPrimary: 'rgba(24, 26, 28, 1)',
  lightForegroundQuaternary: 'rgba(24, 26, 28, 0.18)',
  lightForegroundSecondary: 'rgba(24, 26, 28, 0.56)',
  lightForegroundTertiary: 'rgba(24, 26, 28, 0.33)',
  lightOverlayPrimary: 'rgba(0, 0, 0, 0.3)',
  lightSeparatorPrimary: 'rgba(5, 26, 46, 0.05)',
  lightSurfaceContainer: 'rgba(255, 255, 255, 1)',
  lightSurfaceNonModal: 'rgba(255, 255, 255, 1)',
  darkBackgroundPrimary: 'rgba(21, 23, 25, 1)',
  darkBorderDisabled: 'rgba(228, 230, 232, 0.08)',
  darkBorderFocusedOnTint: 'rgba(0, 0, 0, 0.38)',
  darkBorderInverted: 'rgba(24, 26, 28, 1)',
  darkBorderInvertedNone: 'rgba(24, 26, 28, 0)',
  darkBorderNone: 'rgba(255, 255, 255, 0)',
  darkBorderPrimary: 'rgba(255, 255, 255, 1)',
  darkBorderSecondary: 'rgba(228, 230, 232, 0.14)',
  darkBorderTertiary: 'rgba(228, 230, 232, 0.08)',
  darkFillDisabled: 'rgba(228, 230, 232, 0.1)',
  darkFillHovered: 'rgba(255, 255, 255, 0.04)',
  darkFillInverted: 'var(--ref-color-white)',
  darkFillInvertedNone: 'rgba(255, 255, 255, 0)',
  darkFillNone: 'rgba(255, 255, 255, 0)',
  darkFillPressed: 'rgba(255, 255, 255, 0.08)',
  darkFillPrimary: 'rgba(228, 230, 232, 0.04)',
  darkFillQuaternary: 'rgba(120, 120, 128, 0.18)',
  darkFillSecondary: 'rgba(228, 230, 232, 0.08)',
  darkFillTertiary: 'rgba(120, 120, 128, 0.24)',
  darkForegroundDisabled: 'rgba(228, 230, 232, 0.16)',
  darkForegroundInverted: 'rgba(24, 26, 28, 1)',
  darkForegroundInvertedNone: 'rgba(24, 26, 28, 0)',
  darkForegroundNone: 'rgba(255, 255, 255, 0)',
  darkForegroundPrimary: 'rgba(255, 255, 255, 1)',
  darkForegroundQuaternary: 'rgba(228, 230, 232, 0.16)',
  darkForegroundSecondary: 'rgba(228, 230, 232, 0.47)',
  darkForegroundTertiary: 'rgba(228, 230, 232, 0.26)',
  darkOverlayPrimary: 'rgba(0, 0, 0, 0.8)',
  darkSeparatorPrimary: 'rgba(209, 230, 250, 0.05)',
  darkSurfaceContainer: 'rgba(28, 30, 32, 1)',
  darkSurfaceNonModal: 'rgba(38, 40, 42, 1)',
  lightNegativePrimary: 'var(--ref-color-red5)',
  lightNegativeSecondary: 'var(--ref-color-red3)',
  lightNegativeTertiary: 'var(--ref-color-red2)',
  lightPositivePrimary: 'var(--ref-color-green5)',
  lightPositiveSecondary: 'var(--ref-color-green3)',
  lightPositiveTertiary: 'var(--ref-color-green2)',
  lightSystemMainPrimary: 'var(--ref-color-purple4)',
  lightSystemMainSecondary: 'var(--ref-color-purple3)',
  lightSystemMainTertiary: 'var(--ref-color-purple2)',
  lightSystemSubPrimary: 'var(--ref-color-blue5)',
  lightSystemSubSecondary: 'var(--ref-color-blue3)',
  lightSystemSubTertiary: 'var(--ref-color-blue2)',
  lightWarningPrimary: 'var(--ref-color-orange5)',
  lightWarningSecondary: 'var(--ref-color-orange3)',
  lightWarningTertiary: 'var(--ref-color-orange2)',
  darkNegativePrimary: 'var(--ref-color-red5)',
  darkNegativeSecondary: 'var(--ref-color-red3)',
  darkNegativeTertiary: 'var(--ref-color-red2)',
  darkPositivePrimary: 'var(--ref-color-green5)',
  darkPositiveSecondary: 'var(--ref-color-green3)',
  darkPositiveTertiary: 'var(--ref-color-green2)',
  darkSystemMainPrimary: 'var(--ref-color-purple4)',
  darkSystemMainSecondary: 'var(--ref-color-purple3)',
  darkSystemMainTertiary: 'var(--ref-color-purple2)',
  darkSystemSubPrimary: 'var(--ref-color-blue5)',
  darkSystemSubSecondary: 'var(--ref-color-blue3)',
  darkSystemSubTertiary: 'var(--ref-color-blue2)',
  darkWarningPrimary: 'var(--ref-color-orange5)',
  darkWarningSecondary: 'var(--ref-color-orange3)',
  darkWarningTertiary: 'var(--ref-color-orange2)',
}
const VAR_NAME = {
  colorBackgroundPrimary: '--sem-base-color-backgroundPrimary',
  colorBorderDisabled: '--sem-base-color-borderDisabled',
  colorBorderFocusedOnTint: '--sem-base-color-borderFocusedOnTint',
  colorBorderInverted: '--sem-base-color-borderInverted',
  colorBorderInvertedNone: '--sem-base-color-borderInvertedNone',
  colorBorderNone: '--sem-base-color-borderNone',
  colorBorderPrimary: '--sem-base-color-borderPrimary',
  colorBorderSecondary: '--sem-base-color-borderSecondary',
  colorBorderTertiary: '--sem-base-color-borderTertiary',
  colorFillDisabled: '--sem-base-color-fillDisabled',
  colorFillHovered: '--sem-base-color-fillHovered',
  colorFillInverted: '--sem-base-color-fillInverted',
  colorFillInvertedNone: '--sem-base-color-fillInvertedNone',
  colorFillNone: '--sem-base-color-fillNone',
  colorFillPressed: '--sem-base-color-fillPressed',
  colorFillPrimary: '--sem-base-color-fillPrimary',
  colorFillQuaternary: '--sem-base-color-fillQuaternary',
  colorFillSecondary: '--sem-base-color-fillSecondary',
  colorFillTertiary: '--sem-base-color-fillTertiary',
  colorForegroundDisabled: '--sem-base-color-foregroundDisabled',
  colorForegroundInverted: '--sem-base-color-foregroundInverted',
  colorForegroundInvertedNone: '--sem-base-color-foregroundInvertedNone',
  colorForegroundNone: '--sem-base-color-foregroundNone',
  colorForegroundPrimary: '--sem-base-color-foregroundPrimary',
  colorForegroundQuaternary: '--sem-base-color-foregroundQuaternary',
  colorForegroundSecondary: '--sem-base-color-foregroundSecondary',
  colorForegroundTertiary: '--sem-base-color-foregroundTertiary',
  colorOverlayPrimary: '--sem-base-color-overlayPrimary',
  colorSeparatorPrimary: '--sem-base-color-separatorPrimary',
  colorSurfaceContainer: '--sem-base-color-surfaceContainer',
  colorSurfaceNonModal: '--sem-base-color-surfaceNonModal',
  colorNegativePrimary: '--sem-base-color-negativePrimary',
  colorNegativeSecondary: '--sem-base-color-negativeSecondary',
  colorNegativeTertiary: '--sem-base-color-negativeTertiary',
  colorPositivePrimary: '--sem-base-color-positivePrimary',
  colorPositiveSecondary: '--sem-base-color-positiveSecondary',
  colorPositiveTertiary: '--sem-base-color-positiveTertiary',
  colorSystemMainPrimary: '--sem-base-color-systemMainPrimary',
  colorSystemMainSecondary: '--sem-base-color-systemMainSecondary',
  colorSystemMainTertiary: '--sem-base-color-systemMainTertiary',
  colorSystemSubPrimary: '--sem-base-color-systemSubPrimary',
  colorSystemSubSecondary: '--sem-base-color-systemSubSecondary',
  colorSystemSubTertiary: '--sem-base-color-systemSubTertiary',
  colorWarningPrimary: '--sem-base-color-warningPrimary',
  colorWarningSecondary: '--sem-base-color-warningSecondary',
  colorWarningTertiary: '--sem-base-color-warningTertiary',
} as const
export const semanticColorVars = {
  backgroundPrimary: `var(${VAR_NAME['colorBackgroundPrimary']})`,
  borderDisabled: `var(${VAR_NAME['colorBorderDisabled']})`,
  borderFocusedOnTint: `var(${VAR_NAME['colorBorderFocusedOnTint']})`,
  borderInverted: `var(${VAR_NAME['colorBorderInverted']})`,
  borderInvertedNone: `var(${VAR_NAME['colorBorderInvertedNone']})`,
  borderNone: `var(${VAR_NAME['colorBorderNone']})`,
  borderPrimary: `var(${VAR_NAME['colorBorderPrimary']})`,
  borderSecondary: `var(${VAR_NAME['colorBorderSecondary']})`,
  borderTertiary: `var(${VAR_NAME['colorBorderTertiary']})`,
  fillDisabled: `var(${VAR_NAME['colorFillDisabled']})`,
  fillHovered: `var(${VAR_NAME['colorFillHovered']})`,
  fillInverted: `var(${VAR_NAME['colorFillInverted']})`,
  fillInvertedNone: `var(${VAR_NAME['colorFillInvertedNone']})`,
  fillNone: `var(${VAR_NAME['colorFillNone']})`,
  fillPressed: `var(${VAR_NAME['colorFillPressed']})`,
  fillPrimary: `var(${VAR_NAME['colorFillPrimary']})`,
  fillQuaternary: `var(${VAR_NAME['colorFillQuaternary']})`,
  fillSecondary: `var(${VAR_NAME['colorFillSecondary']})`,
  fillTertiary: `var(${VAR_NAME['colorFillTertiary']})`,
  foregroundDisabled: `var(${VAR_NAME['colorForegroundDisabled']})`,
  foregroundInverted: `var(${VAR_NAME['colorForegroundInverted']})`,
  foregroundInvertedNone: `var(${VAR_NAME['colorForegroundInvertedNone']})`,
  foregroundNone: `var(${VAR_NAME['colorForegroundNone']})`,
  foregroundPrimary: `var(${VAR_NAME['colorForegroundPrimary']})`,
  foregroundQuaternary: `var(${VAR_NAME['colorForegroundQuaternary']})`,
  foregroundSecondary: `var(${VAR_NAME['colorForegroundSecondary']})`,
  foregroundTertiary: `var(${VAR_NAME['colorForegroundTertiary']})`,
  overlayPrimary: `var(${VAR_NAME['colorOverlayPrimary']})`,
  separatorPrimary: `var(${VAR_NAME['colorSeparatorPrimary']})`,
  surfaceContainer: `var(${VAR_NAME['colorSurfaceContainer']})`,
  surfaceNonModal: `var(${VAR_NAME['colorSurfaceNonModal']})`,
  negativePrimary: `var(${VAR_NAME['colorNegativePrimary']})`,
  negativeSecondary: `var(${VAR_NAME['colorNegativeSecondary']})`,
  negativeTertiary: `var(${VAR_NAME['colorNegativeTertiary']})`,
  positivePrimary: `var(${VAR_NAME['colorPositivePrimary']})`,
  positiveSecondary: `var(${VAR_NAME['colorPositiveSecondary']})`,
  positiveTertiary: `var(${VAR_NAME['colorPositiveTertiary']})`,
  systemMainPrimary: `var(${VAR_NAME['colorSystemMainPrimary']})`,
  systemMainSecondary: `var(${VAR_NAME['colorSystemMainSecondary']})`,
  systemMainTertiary: `var(${VAR_NAME['colorSystemMainTertiary']})`,
  systemSubPrimary: `var(${VAR_NAME['colorSystemSubPrimary']})`,
  systemSubSecondary: `var(${VAR_NAME['colorSystemSubSecondary']})`,
  systemSubTertiary: `var(${VAR_NAME['colorSystemSubTertiary']})`,
  warningPrimary: `var(${VAR_NAME['colorWarningPrimary']})`,
  warningSecondary: `var(${VAR_NAME['colorWarningSecondary']})`,
  warningTertiary: `var(${VAR_NAME['colorWarningTertiary']})`,
} as const
export const semanticLightTheme = {
  [VAR_NAME['colorBackgroundPrimary']]: color['lightBackgroundPrimary'],
  [VAR_NAME['colorBorderDisabled']]: color['lightBorderDisabled'],
  [VAR_NAME['colorBorderFocusedOnTint']]: color['lightBorderFocusedOnTint'],
  [VAR_NAME['colorBorderInverted']]: color['lightBorderInverted'],
  [VAR_NAME['colorBorderInvertedNone']]: color['lightBorderInvertedNone'],
  [VAR_NAME['colorBorderNone']]: color['lightBorderNone'],
  [VAR_NAME['colorBorderPrimary']]: color['lightBorderPrimary'],
  [VAR_NAME['colorBorderSecondary']]: color['lightBorderSecondary'],
  [VAR_NAME['colorBorderTertiary']]: color['lightBorderTertiary'],
  [VAR_NAME['colorFillDisabled']]: color['lightFillDisabled'],
  [VAR_NAME['colorFillHovered']]: color['lightFillHovered'],
  [VAR_NAME['colorFillInverted']]: color['lightFillInverted'],
  [VAR_NAME['colorFillInvertedNone']]: color['lightFillInvertedNone'],
  [VAR_NAME['colorFillNone']]: color['lightFillNone'],
  [VAR_NAME['colorFillPressed']]: color['lightFillPressed'],
  [VAR_NAME['colorFillPrimary']]: color['lightFillPrimary'],
  [VAR_NAME['colorFillQuaternary']]: color['lightFillQuaternary'],
  [VAR_NAME['colorFillSecondary']]: color['lightFillSecondary'],
  [VAR_NAME['colorFillTertiary']]: color['lightFillTertiary'],
  [VAR_NAME['colorForegroundDisabled']]: color['lightForegroundDisabled'],
  [VAR_NAME['colorForegroundInverted']]: color['lightForegroundInverted'],
  [VAR_NAME['colorForegroundInvertedNone']]: color['lightForegroundInvertedNone'],
  [VAR_NAME['colorForegroundNone']]: color['lightForegroundNone'],
  [VAR_NAME['colorForegroundPrimary']]: color['lightForegroundPrimary'],
  [VAR_NAME['colorForegroundQuaternary']]: color['lightForegroundQuaternary'],
  [VAR_NAME['colorForegroundSecondary']]: color['lightForegroundSecondary'],
  [VAR_NAME['colorForegroundTertiary']]: color['lightForegroundTertiary'],
  [VAR_NAME['colorOverlayPrimary']]: color['lightOverlayPrimary'],
  [VAR_NAME['colorSeparatorPrimary']]: color['lightSeparatorPrimary'],
  [VAR_NAME['colorSurfaceContainer']]: color['lightSurfaceContainer'],
  [VAR_NAME['colorSurfaceNonModal']]: color['lightSurfaceNonModal'],
  [VAR_NAME['colorNegativePrimary']]: color['lightNegativePrimary'],
  [VAR_NAME['colorNegativeSecondary']]: color['lightNegativeSecondary'],
  [VAR_NAME['colorNegativeTertiary']]: color['lightNegativeTertiary'],
  [VAR_NAME['colorPositivePrimary']]: color['lightPositivePrimary'],
  [VAR_NAME['colorPositiveSecondary']]: color['lightPositiveSecondary'],
  [VAR_NAME['colorPositiveTertiary']]: color['lightPositiveTertiary'],
  [VAR_NAME['colorSystemMainPrimary']]: color['lightSystemMainPrimary'],
  [VAR_NAME['colorSystemMainSecondary']]: color['lightSystemMainSecondary'],
  [VAR_NAME['colorSystemMainTertiary']]: color['lightSystemMainTertiary'],
  [VAR_NAME['colorSystemSubPrimary']]: color['lightSystemSubPrimary'],
  [VAR_NAME['colorSystemSubSecondary']]: color['lightSystemSubSecondary'],
  [VAR_NAME['colorSystemSubTertiary']]: color['lightSystemSubTertiary'],
  [VAR_NAME['colorWarningPrimary']]: color['lightWarningPrimary'],
  [VAR_NAME['colorWarningSecondary']]: color['lightWarningSecondary'],
  [VAR_NAME['colorWarningTertiary']]: color['lightWarningTertiary'],
}
export const semanticDarkTheme = {
  [VAR_NAME['colorBackgroundPrimary']]: color['darkBackgroundPrimary'],
  [VAR_NAME['colorBorderDisabled']]: color['darkBorderDisabled'],
  [VAR_NAME['colorBorderFocusedOnTint']]: color['darkBorderFocusedOnTint'],
  [VAR_NAME['colorBorderInverted']]: color['darkBorderInverted'],
  [VAR_NAME['colorBorderInvertedNone']]: color['darkBorderInvertedNone'],
  [VAR_NAME['colorBorderNone']]: color['darkBorderNone'],
  [VAR_NAME['colorBorderPrimary']]: color['darkBorderPrimary'],
  [VAR_NAME['colorBorderSecondary']]: color['darkBorderSecondary'],
  [VAR_NAME['colorBorderTertiary']]: color['darkBorderTertiary'],
  [VAR_NAME['colorFillDisabled']]: color['darkFillDisabled'],
  [VAR_NAME['colorFillHovered']]: color['darkFillHovered'],
  [VAR_NAME['colorFillInverted']]: color['darkFillInverted'],
  [VAR_NAME['colorFillInvertedNone']]: color['darkFillInvertedNone'],
  [VAR_NAME['colorFillNone']]: color['darkFillNone'],
  [VAR_NAME['colorFillPressed']]: color['darkFillPressed'],
  [VAR_NAME['colorFillPrimary']]: color['darkFillPrimary'],
  [VAR_NAME['colorFillQuaternary']]: color['darkFillQuaternary'],
  [VAR_NAME['colorFillSecondary']]: color['darkFillSecondary'],
  [VAR_NAME['colorFillTertiary']]: color['darkFillTertiary'],
  [VAR_NAME['colorForegroundDisabled']]: color['darkForegroundDisabled'],
  [VAR_NAME['colorForegroundInverted']]: color['darkForegroundInverted'],
  [VAR_NAME['colorForegroundInvertedNone']]: color['darkForegroundInvertedNone'],
  [VAR_NAME['colorForegroundNone']]: color['darkForegroundNone'],
  [VAR_NAME['colorForegroundPrimary']]: color['darkForegroundPrimary'],
  [VAR_NAME['colorForegroundQuaternary']]: color['darkForegroundQuaternary'],
  [VAR_NAME['colorForegroundSecondary']]: color['darkForegroundSecondary'],
  [VAR_NAME['colorForegroundTertiary']]: color['darkForegroundTertiary'],
  [VAR_NAME['colorOverlayPrimary']]: color['darkOverlayPrimary'],
  [VAR_NAME['colorSeparatorPrimary']]: color['darkSeparatorPrimary'],
  [VAR_NAME['colorSurfaceContainer']]: color['darkSurfaceContainer'],
  [VAR_NAME['colorSurfaceNonModal']]: color['darkSurfaceNonModal'],
  [VAR_NAME['colorNegativePrimary']]: color['darkNegativePrimary'],
  [VAR_NAME['colorNegativeSecondary']]: color['darkNegativeSecondary'],
  [VAR_NAME['colorNegativeTertiary']]: color['darkNegativeTertiary'],
  [VAR_NAME['colorPositivePrimary']]: color['darkPositivePrimary'],
  [VAR_NAME['colorPositiveSecondary']]: color['darkPositiveSecondary'],
  [VAR_NAME['colorPositiveTertiary']]: color['darkPositiveTertiary'],
  [VAR_NAME['colorSystemMainPrimary']]: color['darkSystemMainPrimary'],
  [VAR_NAME['colorSystemMainSecondary']]: color['darkSystemMainSecondary'],
  [VAR_NAME['colorSystemMainTertiary']]: color['darkSystemMainTertiary'],
  [VAR_NAME['colorSystemSubPrimary']]: color['darkSystemSubPrimary'],
  [VAR_NAME['colorSystemSubSecondary']]: color['darkSystemSubSecondary'],
  [VAR_NAME['colorSystemSubTertiary']]: color['darkSystemSubTertiary'],
  [VAR_NAME['colorWarningPrimary']]: color['darkWarningPrimary'],
  [VAR_NAME['colorWarningSecondary']]: color['darkWarningSecondary'],
  [VAR_NAME['colorWarningTertiary']]: color['darkWarningTertiary'],
}
