sonar.projectName=orbit-ui-eclipse
sonar.projectKey=orbit-ui-eclipse
sonar.projectBaseDir=packages/clay/mint
sonar.sources=src
sonar.test=src/**/*.test.*
sonar.inclusions=src/**/*.ts, src/**/*.tsx
sonar.exclusions=node_modules, **/*.css.ts, **/*.stories.tsx

sonar.test.inclusions=src/**/*.test.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.language=ts
sonar.verbose=false
sonar.qualitygate.wait=true
