const color = {
  lightBackgroundPrimary: 'rgba(243, 245, 247, 1)',
  lightBorderDisabled: 'rgba(24, 26, 28, 0.11)',
  lightBorderFocusedOnTint: 'rgba(0, 0, 0, 0.38)',
  lightBorderInverted: 'rgba(255, 255, 255, 1)',
  lightBorderInvertedNone: 'rgba(255, 255, 255, 0)',
  lightBorderNone: 'rgba(0, 0, 0, 0)',
  lightBorderPrimary: 'rgba(24, 26, 28, 1)',
  lightBorderQuaternary: 'rgba(24, 26, 28, 0.08)',
  lightBorderSecondary: 'rgba(24, 26, 28, 0.18)',
  lightBorderTertiary: 'rgba(24, 26, 28, 0.11)',
  lightFillDisabled: 'rgba(0, 0, 20, 0.1)',
  lightFillHovered: 'rgba(0, 0, 0, 0.04)',
  lightFillHoveredOnInverted: 'rgba(255, 255, 255, 0.04)',
  lightFillInverted: 'rgba(0, 0, 0, 1)',
  lightFillInvertedNone: 'rgba(0, 0, 0, 0)',
  lightFillNone: 'rgba(0, 0, 0, 0)',
  lightFillPressed: 'rgba(0, 0, 0, 0.08)',
  lightFillPressedOnInverted: 'rgba(255, 255, 255, 0.1)',
  lightFillPrimary: 'rgba(0, 0, 51, 0.04)',
  lightFillSecondary: 'rgba(0, 0, 20, 0.1)',
  lightForegroundDisabled: 'rgba(24, 26, 28, 0.18)',
  lightForegroundInverted: 'rgba(255, 255, 255, 1)',
  lightForegroundInvertedNone: 'rgba(255, 255, 255, 0)',
  lightForegroundNone: 'rgba(0, 0, 0, 0)',
  lightForegroundPrimary: 'rgba(24, 26, 28, 1)',
  lightForegroundQuaternary: 'rgba(24, 26, 28, 0.33)',
  lightForegroundSecondary: 'rgba(24, 26, 28, 0.78)',
  lightForegroundTertiary: 'rgba(24, 26, 28, 0.56)',
  lightOverlayPrimary: 'rgba(0, 0, 0, 0.5)',
  lightSeparatorPrimary: 'rgba(24, 26, 28, 0.06)',
  lightShadowLevel1: 'rgba(0, 0, 0, 0.06)',
  lightShadowLevel2: 'rgba(0, 0, 0, 0.12)',
  lightShadowLevel3: 'rgba(0, 0, 0, 0.18)',
  lightSurfaceContainer: 'rgba(255, 255, 255, 1)',
  lightSurfaceNonModal: 'rgba(255, 255, 255, 1)',
  darkBackgroundPrimary: 'rgba(21, 23, 25, 1)',
  darkBorderDisabled: 'rgba(228, 230, 232, 0.08)',
  darkBorderFocusedOnTint: 'rgba(0, 0, 0, 0.38)',
  darkBorderInverted: 'rgba(0, 0, 0, 1)',
  darkBorderInvertedNone: 'rgba(0, 0, 0, 0)',
  darkBorderNone: 'rgba(255, 255, 255, 0)',
  darkBorderPrimary: 'rgba(255, 255, 255, 1)',
  darkBorderQuaternary: 'rgba(228, 230, 232, 0.08)',
  darkBorderSecondary: 'rgba(228, 230, 232, 0.14)',
  darkBorderTertiary: 'rgba(228, 230, 232, 0.1)',
  darkFillDisabled: 'rgba(228, 230, 232, 0.08)',
  darkFillHovered: 'rgba(255, 255, 255, 0.04)',
  darkFillHoveredOnInverted: 'rgba(0, 0, 0, 0.04)',
  darkFillInverted: 'rgba(255, 255, 255, 1)',
  darkFillInvertedNone: 'rgba(255, 255, 255, 0)',
  darkFillNone: 'rgba(255, 255, 255, 0)',
  darkFillPressed: 'rgba(255, 255, 255, 0.08)',
  darkFillPressedOnInverted: 'rgba(0, 0, 0, 0.08)',
  darkFillPrimary: 'rgba(228, 230, 232, 0.04)',
  darkFillSecondary: 'rgba(228, 230, 232, 0.08)',
  darkForegroundDisabled: 'rgba(228, 230, 232, 0.16)',
  darkForegroundInverted: 'rgba(24, 26, 28, 1)',
  darkForegroundInvertedNone: 'rgba(0, 0, 0, 0)',
  darkForegroundNone: 'rgba(255, 255, 255, 0)',
  darkForegroundPrimary: 'rgba(255, 255, 255, 1)',
  darkForegroundQuaternary: 'rgba(228, 230, 232, 0.26)',
  darkForegroundSecondary: 'rgba(228, 230, 232, 0.78)',
  darkForegroundTertiary: 'rgba(228, 230, 232, 0.47)',
  darkOverlayPrimary: 'rgba(0, 0, 0, 0.8)',
  darkSeparatorPrimary: 'rgba(228, 230, 232, 0.06)',
  darkShadowLevel1: 'rgba(0, 0, 0, 0.3)',
  darkShadowLevel2: 'rgba(0, 0, 0, 0.5)',
  darkShadowLevel3: 'rgba(0, 0, 0, 0.8)',
  darkSurfaceContainer: 'rgba(28, 30, 32, 1)',
  darkSurfaceNonModal: 'rgba(38, 40, 42, 1)',
  lightBenefitPrimary: 'var(--ref-color-purple5)',
  lightBenefitSecondary: 'var(--ref-color-purple6)',
  lightBenefitTertiary: 'var(--ref-color-purple1)',
  lightNegativePrimary: 'var(--ref-color-red5)',
  lightNegativeSecondary: 'var(--ref-color-red6)',
  lightNegativeTertiary: 'var(--ref-color-red1)',
  lightPositivePrimary: 'var(--ref-color-green5)',
  lightPositiveSecondary: 'var(--ref-color-green6)',
  lightPositiveTertiary: 'var(--ref-color-green1)',
  lightSystemMainPrimary: '#2563EB',
  lightSystemMainSecondary: '#64748B',
  lightSystemMainTertiary: '#DBEAFE',
  lightSystemSubPrimary: '#6366F1',
  lightSystemSubSecondary: '#818CF8',
  lightSystemSubTertiary: '#E0E7FF',
  lightWarningPrimary: 'var(--ref-color-orange5)',
  lightWarningSecondary: 'var(--ref-color-orange6)',
  lightWarningTertiary: 'var(--ref-color-orange1)',
  darkBenefitPrimary: 'var(--ref-color-purple6)',
  darkBenefitSecondary: 'var(--ref-color-purple6)',
  darkBenefitTertiary: 'var(--ref-color-purple1)',
  darkNegativePrimary: 'var(--ref-color-red5)',
  darkNegativeSecondary: 'var(--ref-color-red6)',
  darkNegativeTertiary: 'var(--ref-color-red1)',
  darkPositivePrimary: 'var(--ref-color-green5)',
  darkPositiveSecondary: 'var(--ref-color-green6)',
  darkPositiveTertiary: 'var(--ref-color-green1)',
  darkSystemMainPrimary: '#3B82F6',
  darkSystemMainSecondary: '#94A3B8',
  darkSystemMainTertiary: '#1E3A5F',
  darkSystemSubPrimary: '#818CF8',
  darkSystemSubSecondary: '#A5B4FC',
  darkSystemSubTertiary: '#312E81',
  darkWarningPrimary: 'var(--ref-color-orange5)',
  darkWarningSecondary: 'var(--ref-color-orange6)',
  darkWarningTertiary: 'var(--ref-color-orange1)',
}
const VAR_NAME = {
  colorBackgroundPrimary: '--sem-eclipse-color-backgroundPrimary',
  colorBorderDisabled: '--sem-eclipse-color-borderDisabled',
  colorBorderFocusedOnTint: '--sem-eclipse-color-borderFocusedOnTint',
  colorBorderInverted: '--sem-eclipse-color-borderInverted',
  colorBorderInvertedNone: '--sem-eclipse-color-borderInvertedNone',
  colorBorderNone: '--sem-eclipse-color-borderNone',
  colorBorderPrimary: '--sem-eclipse-color-borderPrimary',
  colorBorderQuaternary: '--sem-eclipse-color-borderQuaternary',
  colorBorderSecondary: '--sem-eclipse-color-borderSecondary',
  colorBorderTertiary: '--sem-eclipse-color-borderTertiary',
  colorFillDisabled: '--sem-eclipse-color-fillDisabled',
  colorFillHovered: '--sem-eclipse-color-fillHovered',
  colorFillHoveredOnInverted: '--sem-eclipse-color-fillHoveredOnInverted',
  colorFillInverted: '--sem-eclipse-color-fillInverted',
  colorFillInvertedNone: '--sem-eclipse-color-fillInvertedNone',
  colorFillNone: '--sem-eclipse-color-fillNone',
  colorFillPressed: '--sem-eclipse-color-fillPressed',
  colorFillPressedOnInverted: '--sem-eclipse-color-fillPressedOnInverted',
  colorFillPrimary: '--sem-eclipse-color-fillPrimary',
  colorFillSecondary: '--sem-eclipse-color-fillSecondary',
  colorForegroundDisabled: '--sem-eclipse-color-foregroundDisabled',
  colorForegroundInverted: '--sem-eclipse-color-foregroundInverted',
  colorForegroundInvertedNone: '--sem-eclipse-color-foregroundInvertedNone',
  colorForegroundNone: '--sem-eclipse-color-foregroundNone',
  colorForegroundPrimary: '--sem-eclipse-color-foregroundPrimary',
  colorForegroundQuaternary: '--sem-eclipse-color-foregroundQuaternary',
  colorForegroundSecondary: '--sem-eclipse-color-foregroundSecondary',
  colorForegroundTertiary: '--sem-eclipse-color-foregroundTertiary',
  colorOverlayPrimary: '--sem-eclipse-color-overlayPrimary',
  colorSeparatorPrimary: '--sem-eclipse-color-separatorPrimary',
  colorShadowLevel1: '--sem-eclipse-color-shadowLevel1',
  colorShadowLevel2: '--sem-eclipse-color-shadowLevel2',
  colorShadowLevel3: '--sem-eclipse-color-shadowLevel3',
  colorSurfaceContainer: '--sem-eclipse-color-surfaceContainer',
  colorSurfaceNonModal: '--sem-eclipse-color-surfaceNonModal',
  colorBenefitPrimary: '--sem-eclipse-color-benefitPrimary',
  colorBenefitSecondary: '--sem-eclipse-color-benefitSecondary',
  colorBenefitTertiary: '--sem-eclipse-color-benefitTertiary',
  colorNegativePrimary: '--sem-eclipse-color-negativePrimary',
  colorNegativeSecondary: '--sem-eclipse-color-negativeSecondary',
  colorNegativeTertiary: '--sem-eclipse-color-negativeTertiary',
  colorPositivePrimary: '--sem-eclipse-color-positivePrimary',
  colorPositiveSecondary: '--sem-eclipse-color-positiveSecondary',
  colorPositiveTertiary: '--sem-eclipse-color-positiveTertiary',
  colorSystemMainPrimary: '--sem-eclipse-color-systemMainPrimary',
  colorSystemMainSecondary: '--sem-eclipse-color-systemMainSecondary',
  colorSystemMainTertiary: '--sem-eclipse-color-systemMainTertiary',
  colorSystemSubPrimary: '--sem-eclipse-color-systemSubPrimary',
  colorSystemSubSecondary: '--sem-eclipse-color-systemSubSecondary',
  colorSystemSubTertiary: '--sem-eclipse-color-systemSubTertiary',
  colorWarningPrimary: '--sem-eclipse-color-warningPrimary',
  colorWarningSecondary: '--sem-eclipse-color-warningSecondary',
  colorWarningTertiary: '--sem-eclipse-color-warningTertiary',
} as const
export const semanticColorVars = {
  backgroundPrimary: `var(${VAR_NAME['colorBackgroundPrimary']})`,
  borderDisabled: `var(${VAR_NAME['colorBorderDisabled']})`,
  borderFocusedOnTint: `var(${VAR_NAME['colorBorderFocusedOnTint']})`,
  borderInverted: `var(${VAR_NAME['colorBorderInverted']})`,
  borderInvertedNone: `var(${VAR_NAME['colorBorderInvertedNone']})`,
  borderNone: `var(${VAR_NAME['colorBorderNone']})`,
  borderPrimary: `var(${VAR_NAME['colorBorderPrimary']})`,
  borderQuaternary: `var(${VAR_NAME['colorBorderQuaternary']})`,
  borderSecondary: `var(${VAR_NAME['colorBorderSecondary']})`,
  borderTertiary: `var(${VAR_NAME['colorBorderTertiary']})`,
  fillDisabled: `var(${VAR_NAME['colorFillDisabled']})`,
  fillHovered: `var(${VAR_NAME['colorFillHovered']})`,
  fillHoveredOnInverted: `var(${VAR_NAME['colorFillHoveredOnInverted']})`,
  fillInverted: `var(${VAR_NAME['colorFillInverted']})`,
  fillInvertedNone: `var(${VAR_NAME['colorFillInvertedNone']})`,
  fillNone: `var(${VAR_NAME['colorFillNone']})`,
  fillPressed: `var(${VAR_NAME['colorFillPressed']})`,
  fillPressedOnInverted: `var(${VAR_NAME['colorFillPressedOnInverted']})`,
  fillPrimary: `var(${VAR_NAME['colorFillPrimary']})`,
  fillSecondary: `var(${VAR_NAME['colorFillSecondary']})`,
  foregroundDisabled: `var(${VAR_NAME['colorForegroundDisabled']})`,
  foregroundInverted: `var(${VAR_NAME['colorForegroundInverted']})`,
  foregroundInvertedNone: `var(${VAR_NAME['colorForegroundInvertedNone']})`,
  foregroundNone: `var(${VAR_NAME['colorForegroundNone']})`,
  foregroundPrimary: `var(${VAR_NAME['colorForegroundPrimary']})`,
  foregroundQuaternary: `var(${VAR_NAME['colorForegroundQuaternary']})`,
  foregroundSecondary: `var(${VAR_NAME['colorForegroundSecondary']})`,
  foregroundTertiary: `var(${VAR_NAME['colorForegroundTertiary']})`,
  overlayPrimary: `var(${VAR_NAME['colorOverlayPrimary']})`,
  separatorPrimary: `var(${VAR_NAME['colorSeparatorPrimary']})`,
  shadowLevel1: `var(${VAR_NAME['colorShadowLevel1']})`,
  shadowLevel2: `var(${VAR_NAME['colorShadowLevel2']})`,
  shadowLevel3: `var(${VAR_NAME['colorShadowLevel3']})`,
  surfaceContainer: `var(${VAR_NAME['colorSurfaceContainer']})`,
  surfaceNonModal: `var(${VAR_NAME['colorSurfaceNonModal']})`,
  benefitPrimary: `var(${VAR_NAME['colorBenefitPrimary']})`,
  benefitSecondary: `var(${VAR_NAME['colorBenefitSecondary']})`,
  benefitTertiary: `var(${VAR_NAME['colorBenefitTertiary']})`,
  negativePrimary: `var(${VAR_NAME['colorNegativePrimary']})`,
  negativeSecondary: `var(${VAR_NAME['colorNegativeSecondary']})`,
  negativeTertiary: `var(${VAR_NAME['colorNegativeTertiary']})`,
  positivePrimary: `var(${VAR_NAME['colorPositivePrimary']})`,
  positiveSecondary: `var(${VAR_NAME['colorPositiveSecondary']})`,
  positiveTertiary: `var(${VAR_NAME['colorPositiveTertiary']})`,
  systemMainPrimary: `var(${VAR_NAME['colorSystemMainPrimary']})`,
  systemMainSecondary: `var(${VAR_NAME['colorSystemMainSecondary']})`,
  systemMainTertiary: `var(${VAR_NAME['colorSystemMainTertiary']})`,
  systemSubPrimary: `var(${VAR_NAME['colorSystemSubPrimary']})`,
  systemSubSecondary: `var(${VAR_NAME['colorSystemSubSecondary']})`,
  systemSubTertiary: `var(${VAR_NAME['colorSystemSubTertiary']})`,
  warningPrimary: `var(${VAR_NAME['colorWarningPrimary']})`,
  warningSecondary: `var(${VAR_NAME['colorWarningSecondary']})`,
  warningTertiary: `var(${VAR_NAME['colorWarningTertiary']})`,
} as const
export const semanticLightTheme = {
  [VAR_NAME['colorBackgroundPrimary']]: color['lightBackgroundPrimary'],
  [VAR_NAME['colorBorderDisabled']]: color['lightBorderDisabled'],
  [VAR_NAME['colorBorderFocusedOnTint']]: color['lightBorderFocusedOnTint'],
  [VAR_NAME['colorBorderInverted']]: color['lightBorderInverted'],
  [VAR_NAME['colorBorderInvertedNone']]: color['lightBorderInvertedNone'],
  [VAR_NAME['colorBorderNone']]: color['lightBorderNone'],
  [VAR_NAME['colorBorderPrimary']]: color['lightBorderPrimary'],
  [VAR_NAME['colorBorderQuaternary']]: color['lightBorderQuaternary'],
  [VAR_NAME['colorBorderSecondary']]: color['lightBorderSecondary'],
  [VAR_NAME['colorBorderTertiary']]: color['lightBorderTertiary'],
  [VAR_NAME['colorFillDisabled']]: color['lightFillDisabled'],
  [VAR_NAME['colorFillHovered']]: color['lightFillHovered'],
  [VAR_NAME['colorFillHoveredOnInverted']]: color['lightFillHoveredOnInverted'],
  [VAR_NAME['colorFillInverted']]: color['lightFillInverted'],
  [VAR_NAME['colorFillInvertedNone']]: color['lightFillInvertedNone'],
  [VAR_NAME['colorFillNone']]: color['lightFillNone'],
  [VAR_NAME['colorFillPressed']]: color['lightFillPressed'],
  [VAR_NAME['colorFillPressedOnInverted']]: color['lightFillPressedOnInverted'],
  [VAR_NAME['colorFillPrimary']]: color['lightFillPrimary'],
  [VAR_NAME['colorFillSecondary']]: color['lightFillSecondary'],
  [VAR_NAME['colorForegroundDisabled']]: color['lightForegroundDisabled'],
  [VAR_NAME['colorForegroundInverted']]: color['lightForegroundInverted'],
  [VAR_NAME['colorForegroundInvertedNone']]: color['lightForegroundInvertedNone'],
  [VAR_NAME['colorForegroundNone']]: color['lightForegroundNone'],
  [VAR_NAME['colorForegroundPrimary']]: color['lightForegroundPrimary'],
  [VAR_NAME['colorForegroundQuaternary']]: color['lightForegroundQuaternary'],
  [VAR_NAME['colorForegroundSecondary']]: color['lightForegroundSecondary'],
  [VAR_NAME['colorForegroundTertiary']]: color['lightForegroundTertiary'],
  [VAR_NAME['colorOverlayPrimary']]: color['lightOverlayPrimary'],
  [VAR_NAME['colorSeparatorPrimary']]: color['lightSeparatorPrimary'],
  [VAR_NAME['colorShadowLevel1']]: color['lightShadowLevel1'],
  [VAR_NAME['colorShadowLevel2']]: color['lightShadowLevel2'],
  [VAR_NAME['colorShadowLevel3']]: color['lightShadowLevel3'],
  [VAR_NAME['colorSurfaceContainer']]: color['lightSurfaceContainer'],
  [VAR_NAME['colorSurfaceNonModal']]: color['lightSurfaceNonModal'],
  [VAR_NAME['colorBenefitPrimary']]: color['lightBenefitPrimary'],
  [VAR_NAME['colorBenefitSecondary']]: color['lightBenefitSecondary'],
  [VAR_NAME['colorBenefitTertiary']]: color['lightBenefitTertiary'],
  [VAR_NAME['colorNegativePrimary']]: color['lightNegativePrimary'],
  [VAR_NAME['colorNegativeSecondary']]: color['lightNegativeSecondary'],
  [VAR_NAME['colorNegativeTertiary']]: color['lightNegativeTertiary'],
  [VAR_NAME['colorPositivePrimary']]: color['lightPositivePrimary'],
  [VAR_NAME['colorPositiveSecondary']]: color['lightPositiveSecondary'],
  [VAR_NAME['colorPositiveTertiary']]: color['lightPositiveTertiary'],
  [VAR_NAME['colorSystemMainPrimary']]: color['lightSystemMainPrimary'],
  [VAR_NAME['colorSystemMainSecondary']]: color['lightSystemMainSecondary'],
  [VAR_NAME['colorSystemMainTertiary']]: color['lightSystemMainTertiary'],
  [VAR_NAME['colorSystemSubPrimary']]: color['lightSystemSubPrimary'],
  [VAR_NAME['colorSystemSubSecondary']]: color['lightSystemSubSecondary'],
  [VAR_NAME['colorSystemSubTertiary']]: color['lightSystemSubTertiary'],
  [VAR_NAME['colorWarningPrimary']]: color['lightWarningPrimary'],
  [VAR_NAME['colorWarningSecondary']]: color['lightWarningSecondary'],
  [VAR_NAME['colorWarningTertiary']]: color['lightWarningTertiary'],
}
export const semanticDarkTheme = {
  [VAR_NAME['colorBackgroundPrimary']]: color['darkBackgroundPrimary'],
  [VAR_NAME['colorBorderDisabled']]: color['darkBorderDisabled'],
  [VAR_NAME['colorBorderFocusedOnTint']]: color['darkBorderFocusedOnTint'],
  [VAR_NAME['colorBorderInverted']]: color['darkBorderInverted'],
  [VAR_NAME['colorBorderInvertedNone']]: color['darkBorderInvertedNone'],
  [VAR_NAME['colorBorderNone']]: color['darkBorderNone'],
  [VAR_NAME['colorBorderPrimary']]: color['darkBorderPrimary'],
  [VAR_NAME['colorBorderQuaternary']]: color['darkBorderQuaternary'],
  [VAR_NAME['colorBorderSecondary']]: color['darkBorderSecondary'],
  [VAR_NAME['colorBorderTertiary']]: color['darkBorderTertiary'],
  [VAR_NAME['colorFillDisabled']]: color['darkFillDisabled'],
  [VAR_NAME['colorFillHovered']]: color['darkFillHovered'],
  [VAR_NAME['colorFillHoveredOnInverted']]: color['darkFillHoveredOnInverted'],
  [VAR_NAME['colorFillInverted']]: color['darkFillInverted'],
  [VAR_NAME['colorFillInvertedNone']]: color['darkFillInvertedNone'],
  [VAR_NAME['colorFillNone']]: color['darkFillNone'],
  [VAR_NAME['colorFillPressed']]: color['darkFillPressed'],
  [VAR_NAME['colorFillPressedOnInverted']]: color['darkFillPressedOnInverted'],
  [VAR_NAME['colorFillPrimary']]: color['darkFillPrimary'],
  [VAR_NAME['colorFillSecondary']]: color['darkFillSecondary'],
  [VAR_NAME['colorForegroundDisabled']]: color['darkForegroundDisabled'],
  [VAR_NAME['colorForegroundInverted']]: color['darkForegroundInverted'],
  [VAR_NAME['colorForegroundInvertedNone']]: color['darkForegroundInvertedNone'],
  [VAR_NAME['colorForegroundNone']]: color['darkForegroundNone'],
  [VAR_NAME['colorForegroundPrimary']]: color['darkForegroundPrimary'],
  [VAR_NAME['colorForegroundQuaternary']]: color['darkForegroundQuaternary'],
  [VAR_NAME['colorForegroundSecondary']]: color['darkForegroundSecondary'],
  [VAR_NAME['colorForegroundTertiary']]: color['darkForegroundTertiary'],
  [VAR_NAME['colorOverlayPrimary']]: color['darkOverlayPrimary'],
  [VAR_NAME['colorSeparatorPrimary']]: color['darkSeparatorPrimary'],
  [VAR_NAME['colorShadowLevel1']]: color['darkShadowLevel1'],
  [VAR_NAME['colorShadowLevel2']]: color['darkShadowLevel2'],
  [VAR_NAME['colorShadowLevel3']]: color['darkShadowLevel3'],
  [VAR_NAME['colorSurfaceContainer']]: color['darkSurfaceContainer'],
  [VAR_NAME['colorSurfaceNonModal']]: color['darkSurfaceNonModal'],
  [VAR_NAME['colorBenefitPrimary']]: color['darkBenefitPrimary'],
  [VAR_NAME['colorBenefitSecondary']]: color['darkBenefitSecondary'],
  [VAR_NAME['colorBenefitTertiary']]: color['darkBenefitTertiary'],
  [VAR_NAME['colorNegativePrimary']]: color['darkNegativePrimary'],
  [VAR_NAME['colorNegativeSecondary']]: color['darkNegativeSecondary'],
  [VAR_NAME['colorNegativeTertiary']]: color['darkNegativeTertiary'],
  [VAR_NAME['colorPositivePrimary']]: color['darkPositivePrimary'],
  [VAR_NAME['colorPositiveSecondary']]: color['darkPositiveSecondary'],
  [VAR_NAME['colorPositiveTertiary']]: color['darkPositiveTertiary'],
  [VAR_NAME['colorSystemMainPrimary']]: color['darkSystemMainPrimary'],
  [VAR_NAME['colorSystemMainSecondary']]: color['darkSystemMainSecondary'],
  [VAR_NAME['colorSystemMainTertiary']]: color['darkSystemMainTertiary'],
  [VAR_NAME['colorSystemSubPrimary']]: color['darkSystemSubPrimary'],
  [VAR_NAME['colorSystemSubSecondary']]: color['darkSystemSubSecondary'],
  [VAR_NAME['colorSystemSubTertiary']]: color['darkSystemSubTertiary'],
  [VAR_NAME['colorWarningPrimary']]: color['darkWarningPrimary'],
  [VAR_NAME['colorWarningSecondary']]: color['darkWarningSecondary'],
  [VAR_NAME['colorWarningTertiary']]: color['darkWarningTertiary'],
}
